name: OpenAI API Integration

on:
  workflow_dispatch: # Manually trigger karne ke liye

jobs:
  run-openai-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Use OpenAI API Key for API Call
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}} # Secrets me key set ki hai
        run: |
          curl https://api.openai.com/v1/engines/davinci/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "prompt": "Hello! How can I help you?",
            "max_tokens": 10000000
          }'
